### ISSUE TITLE
from: can't read /var/mail/mercury_parser.client

### ISSUE THREAD

**Issue by 123tobias123** [Girbons/mercury-parserpy#4]
Hi there,
I am getting the following error message trying to import the package.
`from: can't read /var/mail/mercury_parser.client`

Please help

**Comment by Girbons** [comment]
Hi @tobi1993,

Could you please share some details?
- OS
- which python version are you using 
- How did you installed the package

**Comment by 123tobias123** [comment]
HI, thank you for your quick answer:
- Ubuntu
- Python 3.6.7
- Command line: pip install mercury-parserpy

**Comment by Girbons** [comment]
Did you installed the package inside a virtualenv?

**Comment by 123tobias123** [comment]
yes conda

**Comment by Girbons** [comment]
How are you executing the python script?

**Comment by 123tobias123** [comment]
Visual Studio Code -> run skript

**Comment by Girbons** [comment]
add `#!/usr/bin/env python3` at the top of the file and try to run it again

**Comment by 123tobias123** [comment]
ok great. Now it works. Thanks you!
Another question I have is what api key I need to use. Is it an api key from mercury to use the service or from the website I want to scrape?  
My plan is to implement this library in scrapy so I just want a parser that can take html/json-objects and return only the main content. I don't need mercury to do the scraping

**Comment by Girbons** [comment]
The original service of mercury web parser is not available anymore, so I think that you need to setup it on your own by getting the [code](https://github.com/postlight/mercury-parser).
I need to change the default API endpoint for that

**Comment by 123tobias123** [comment]
I am not sure if i understood right. If it's not possible to use your parser then why does the project still exist? Can you recommend any other parser that can extract the main content of html text?

**Comment by Girbons** [comment]
Because it needs to be updated, I'm sorry for not keeping this library up to date after the cloud service has been closed.

You can use https://github.com/cbogart/mercury-parserpy that accepts an endpoint of your choice instead of the old one.

Actually I don't know what library you could use.

**Comment by 123tobias123** [comment]
ok thanks for the advice :) i will try that one then
