### ISSUE TITLE
Error "Failed to establish a new connection"

### ISSUE THREAD

**Issue by Leszek-Sieminski** [Girbons/mercury-parserpy#6]
Hi Alessandro!

First of all, thanks for creating this module!

I have successfully installed it and tried to run it on test article:
`from mercury_parser.client import MercuryParser`
`parser = MercuryParser(api_endpoint="http://localhost:3000/")`
`article = parser.parse_article('https://thetremblingyorkie.com/my-yorkie-is-trembling/')`
`article.json()`

However, it returns an error:
`ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /parser?url=https://thetremblingyorkie.com/my-yorkie-is-trembling/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000255C93AE988>: Failed to establish a new connection: [WinError 10061]`))`

I think the reason may be connected to urllib3's unability to open the port, but I'm not sure how to deal with it if it's true. I'm not very fluent in Python yet. I would really appreciate your help.

I'm running this code on Windows 10, JupyterLab in Anaconda.

Thanks!
Leszek

**Comment by Girbons** [comment]
Hi @Leszek-Sieminski, is Mercury Parser API up and running?

**Comment by Leszek-Sieminski** [comment]
I checked and it was a problem with an API, not your module. The message just meant that the API wasn't functioning :) Thanks for help and sorry for creating the issue, it can be closed.

**Comment by Girbons** [comment]
> Thanks for help and sorry for creating the issue, it can be closed.
 
hey @Leszek-Sieminski, nevermind, I'm glad to know that you solved the issue 😄

**Comment by emrebz** [comment]
Hi Leszek, did you find a solution for solving this in Python? I am facing the same issue

**Comment by Leszek-Sieminski** [comment]
Hi Emre, 

yes. This module is exposing an endpoint which listens to requests. You simply need to run it in one process (for example start it in terminal locally or in Python script) and then send the page to it (via another terminal/Python script).

Hope it helps!
Best,
Leszek
